name: Flex
markdown: redcarpet
highlighter: pygments
exclude: ["LICENSE.txt", "README.md"]

baseurl: ""
permalink: /:title/


# Paginate
paginate: 1
paginate_path: "/pagination/page:num/"


# Plugins
gems: 
  - jekyll-multiple-languages-plugin
  - jekyll-paginate


# jekyll-multiple-languages-plugin settings:
languages: ["it", "en", "es"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
